task: "ip_adapter"
sub_task: "inpaint"
experiment_name: ""

# Model Configs
personalized_model: "/mnt/bn/automl-aigc/chengjiaxiang/models/diffusers/stable-diffusion-v1-5"
model_type: "sd1.5"
ip_adapter_model: "/mnt/bn/automl-aigc/chengjiaxiang/models/diffusers/IP-Adapter"
ip_adapter_scale: 1.0
res_adapter_model: "models/res_adapter/sd1.5"
res_adapter_alpha: 1.0


# Inference Configs
width: 256
height: 384
scale_ratio: null  # scale the original image

num_inference_steps: 50
guidance_scale: 7.5
num_images_per_prompt: 2

source_images: ["assets/ip_adapter/inpaint_image.png"]
mask_images: ["assets/ip_adapter/mask.png"]
ip_adapter_images: [
  "assets/ip_adapter/girl.png",
]

prompts: [
  "best quality, high quality",
]

n_prompt: "monochrome, lowres, bad anatomy, worst quality, low quality"

# Other Configs
enable_xformers: false  # Must false for ip-adapter, otherwise error occurs...
enable_compare: true
draw_text: true
seed: 42
device: cuda
split_images: false