task: "controlnet"
sub_task: "text_to_image"
experiment_name: ""


# Model Configs
personalized_model: "/mnt/bn/automl-aigc/chengjiaxiang/models/diffusers/stable-diffusion-v1-5"
model_type: "sd1.5"
controlnet_model: "/mnt/bn/automl-aigc/chengjiaxiang/models/diffusers/control_v11p_sd15_canny"
res_adapter_model: "models/res_adapter/sd1.5"
res_adapter_alpha: 1.0


# Inference Configs
width: null
height: null
scale_ratio: 0.5  # scale the original image

num_inference_steps: 25
guidance_scale: 7.5
num_images_per_prompt: 2

source_images: [
  "assets/controlnet/dog.png",
  "assets/controlnet/bird.png",
]

prompts: [
  "cute dog",
  "bird"
]

n_prompt: "lowres, bad anatomy, worst quality, low quality"


# Other Configs
enable_xformers: true
enable_compare: true
draw_text: true
seed: 42
device: cuda
split_images: false